
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uilogin(object):
    def setupUi(self, uilogin):
        uilogin.setObjectName("uilogin")
        uilogin.resize(822, 703)
        self.stackedWidget = QtWidgets.QStackedWidget(uilogin)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 110, 811, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginpage = QtWidgets.QWidget()
        self.loginpage.setObjectName("loginpage")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.loginpage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 130, 801, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.Username_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.Username_2.setObjectName("Username_2")
        self.horizontalLayout_5.addWidget(self.Username_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.Password_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.Password_2.setObjectName("Password_2")
        self.horizontalLayout_8.addWidget(self.Password_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.loginpage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.loginpage)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 330, 801, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.Submitbutton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.Submitbutton_2.setObjectName("Submitbutton_2")
        self.horizontalLayout_10.addWidget(self.Submitbutton_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.loginpage)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(0, 279, 801, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.signup_button = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.signup_button.setObjectName("signup_button")
        self.horizontalLayout.addWidget(self.signup_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.loginpage)
        self.signup = QtWidgets.QWidget()
        self.signup.setObjectName("signup")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.signup)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(0, 20, 801, 80))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem14)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem15)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.verticalLayout_16.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem17)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_22)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.signup)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(0, 170, 801, 151))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_24.addWidget(self.label_25)
        spacerItem20 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem20)
        self.username_signup = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.username_signup.setObjectName("username_signup")
        self.horizontalLayout_24.addWidget(self.username_signup)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem21)
        self.verticalLayout_17.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem22)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_31.addWidget(self.label_30)
        spacerItem23 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem23)
        self.email_signup = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.email_signup.setObjectName("email_signup")
        self.horizontalLayout_31.addWidget(self.email_signup)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem24)
        self.verticalLayout_17.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_26.addWidget(self.label_26)
        spacerItem26 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem26)
        self.password_signup = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.password_signup.setObjectName("password_signup")
        self.horizontalLayout_26.addWidget(self.password_signup)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem27)
        self.verticalLayout_17.addLayout(self.horizontalLayout_26)
        self.widget = QtWidgets.QWidget(self.signup)
        self.widget.setGeometry(QtCore.QRect(0, 340, 799, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem28)
        self.submit_signup = QtWidgets.QPushButton(self.widget)
        self.submit_signup.setObjectName("submit_signup")
        self.horizontalLayout_27.addWidget(self.submit_signup)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem29)
        self.stackedWidget.addWidget(self.signup)
        self.logged = QtWidgets.QWidget()
        self.logged.setObjectName("logged")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.logged)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 801, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem30)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem31)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.logged)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 130, 801, 151))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem32)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        spacerItem33 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem33)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem34)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.stackedWidget.addWidget(self.logged)
        self.failed = QtWidgets.QWidget()
        self.failed.setObjectName("failed")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.failed)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 801, 80))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem35)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem36)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.failed)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 130, 801, 151))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem37)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        spacerItem38 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem38)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem39)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.stackedWidget.addWidget(self.failed)

        self.retranslateUi(uilogin)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(uilogin)

    def retranslateUi(self, uilogin):
        _translate = QtCore.QCoreApplication.translate
        uilogin.setWindowTitle(_translate("uilogin", "Form"))
        self.label_5.setText(_translate("uilogin", "USER NAME :"))
        self.label_6.setText(_translate("uilogin", "PASSWORD :"))
        self.label_7.setText(_translate("uilogin", "BUY-YOURSELF"))
        self.label_8.setText(_translate("uilogin", "LOGIN"))
        self.Submitbutton_2.setText(_translate("uilogin", "SUBMIT"))
        self.label.setText(_translate("uilogin", "IF NOT ALREADY SIGNED:"))
        self.signup_button.setText(_translate("uilogin", "Sign up"))
        self.label_21.setText(_translate("uilogin", "BUY-YOURSELF"))
        self.label_22.setText(_translate("uilogin", "SIGN UP"))
        self.label_25.setText(_translate("uilogin", "USER NAME :"))
        self.label_30.setText(_translate("uilogin", "EMAIL ID     :"))
        self.label_26.setText(_translate("uilogin", "PASSWORD :"))
        self.submit_signup.setText(_translate("uilogin", "SUBMIT"))
        self.label_11.setText(_translate("uilogin", "BUY-YOURSELF"))
        self.label_12.setText(_translate("uilogin", "LOGGED IN "))
        self.label_13.setText(_translate("uilogin", "BUY-YOURSELF"))
        self.label_14.setText(_translate("uilogin", "USER NAME PASSWORD DIDNT MATCHED"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    uilogin = QtWidgets.QWidget()
    ui = Ui_uilogin()
    ui.setupUi(uilogin)
    uilogin.show()
    sys.exit(app.exec_())
